language: python
dist: xenial
sudo: true

python:
  - 3.9.1
before_install:
  - pip install poetry
install:
  - poetry install -v
  - cp contrib/env-sample .env
script:
  - poetry run flake8 .
  - poetry run pytest